### ISSUE TITLE
Generate board/pin setup from user configuration files

### ISSUE THREAD

**Issue by ROMemories** [future-proof-iot/RIOT-rs#210]

**Comment by chrysn** [comment]
Very rough sketch:

```toml
[board]
# could house multiple, but a build system would look for the
# one thing it can "run" on
mdbt1.part = "nrf52840qiaaf02242ed"

[[led]]
name = "D2"
color = "red"
drive = { gpio = "mdb1.p1.09", level = "active-high" }

[[sensor]]
part = "BMP280"
drive = { scl = "mdb1.p0.11", sda = "mdb1.p0.12" }
```
